#!/usr/bin/env python3
"""Install the local HAR-regression pre-commit hook into .git/hooks/pre-commit.

Run once per clone:
    python scripts/hooks/install_hooks.py

This wires .git/hooks/pre-commit to scripts/hooks/pre_commit_har_gate.py so that
every commit is checked against the LOCAL HAR baseline (real HAR originals never
leave the developer machine; see pre_commit_har_gate.py for the full rationale).
"""
from __future__ import annotations

import stat
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
HOOK_TARGET = REPO_ROOT / "scripts" / "hooks" / "pre_commit_har_gate.py"
GIT_HOOKS_DIR = REPO_ROOT / ".git" / "hooks"
PRE_COMMIT = GIT_HOOKS_DIR / "pre-commit"

# A portable shell shim: works on Git Bash / WSL / macOS / Linux.
# On Windows, Git for Windows runs hooks through its bundled sh.exe, so this is fine.
SHIM = """#!/bin/sh
# Auto-generated by scripts/hooks/install_hooks.py -- do not edit.
# Runs the local HAR baseline regression gate before each commit.
exec "{python}" "{hook}" "$@"
"""


def main() -> int:
    if not GIT_HOOKS_DIR.exists():
        print(f"[install-hooks] not a git repo (missing {GIT_HOOKS_DIR})", file=sys.stderr)
        return 1
    if not HOOK_TARGET.exists():
        print(f"[install-hooks] hook script not found: {HOOK_TARGET}", file=sys.stderr)
        return 1

    python = sys.executable.replace("\\", "/")
    hook = str(HOOK_TARGET).replace("\\", "/")
    PRE_COMMIT.write_text(SHIM.format(python=python, hook=hook), encoding="utf-8")

    # chmod +x (no-op on Windows filesystems but harmless)
    mode = PRE_COMMIT.stat().st_mode
    PRE_COMMIT.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    print(f"[install-hooks] installed: {PRE_COMMIT}")
    print(f"[install-hooks]   -> {python} {hook}")
    print("[install-hooks] done. Every commit now runs the HAR baseline regression gate.")
    print("[install-hooks] bypass once with: git commit --no-verify")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
